"""Which module-level constant holds which hand-maintained table.

Generated by `scripts/audit_tool_annotations.py --write`; do not edit.

`src/lib/_ledger.py` wraps every constant named here so a tool call can declare,
at runtime, which tables it actually read -- the other half of what
`@sourced(...)` promises statically. A constant that disappears from this file is
a table whose reader stops being observable, so `--check` regenerates and
compares rather than trusting the version on disk.
"""

from __future__ import annotations

#: module -> {module-level constant: dataset stem it was loaded from or derived
#: from}. Derived constants are included on purpose: a projection computed at
#: import (`_CATEGORIE = sorted({v["categoria"] for v in _CATALOGO.values()})`) is
#: still the table, and reading it during a call means the call applied it.
TABLE_CONSTANTS: dict[str, dict[str, str]] = {
    "src.tools.atti_giudiziari": {
        "_CODICI_RUOLO": "codici_ruolo",
        "_CU": "contributo_unificato",
        "_TASSI_MORA": "tassi_mora",
        "_TRIBUNALI_COMPETENTI": "tribunali_competenti",
    },
    "src.tools.dichiarazione_redditi": {
        "_CODICI_TRIBUTO": "codici_tributo",
        "_IRPEF": "irpef_scaglioni",
        "_TASSI_LEGALI": "tassi_legali",
    },
    "src.tools.diritto_lavoro": {
        "_IRPEF": "irpef_scaglioni",
        "_PREAVVISO": "preavviso_ccnl",
    },
    "src.tools.fatturazione_avvocati": {
        "_COMPETENZE_PENALE": "parametri_forensi",
        "_CU_CIVILE": "contributo_unificato",
        "_PARAMETRI": "parametri_forensi",
    },
    "src.tools.modelli_atti": {
        "_CATALOGO": "modelli_atti",
        "_CATEGORIE": "modelli_atti",
    },
    "src.tools.privacy_gdpr": {
        "_BASI": "gdpr_basi_giuridiche",
        "_DPIA": "gdpr_dpia_criteri",
        "_SANZIONI": "gdpr_sanzioni",
    },
    "src.tools.procure_quotazioni": {
        "_CU": "contributo_unificato",
        "_PARAMETRI": "parametri_forensi",
    },
    "src.tools.proprieta_successioni": {
        "_SUCCESSIONE": "imposte_successione",
        "_USUFRUTTO": "usufrutto_coefficienti",
    },
    "src.tools.risarcimento_danni": {
        "_DANNO_BIO": "tabella_danno_bio",
        "_MACRO": "tabella_danno_bio",
        "_MICRO": "tabella_danno_bio",
        "_PARENTALE": "tabella_milano_roma",
    },
    "src.tools.rivalutazioni_istat": {
        "_COEFF_RACCORDO": "indici_foi",
        "_COEFF_RACCORDO_TESTO": "indici_foi",
        "_FOI_DATA": "indici_foi",
        "_INDICI_FOI": "indici_foi",
        "_NOTA_RACCORDO": "indici_foi",
        "_RACCORDO_BASI": "indici_foi",
        "_TASSI_LEGALI": "tassi_legali",
        "_VARIAZIONI_UFFICIALI": "indici_foi",
    },
    "src.tools.scadenze_termini": {
        "_FESTIVITA_FISSE": "festivita",
    },
    "src.tools.tassi_interessi": {
        "_TASSI_LEGALI": "tassi_legali",
        "_TASSI_MORA": "tassi_mora",
    },
    "src.tools.varie": {
        "_ATECO": "codici_ateco",
        "_COMUNI": "comuni",
        "_COMUNI_DATA": "comuni",
        "_FESTIVITA": "festivita",
        "_STATI_ESTERI": "comuni",
        "_VIOLAZIONI": "violazioni_patente",
    },
}
