"""Which module-level constant holds which hand-maintained table.

Generated by `scripts/audit_tool_annotations.py --write`; do not edit.

`src/lib/_ledger.py` wraps every constant named here so a tool call can declare,
at runtime, which tables it actually read -- the other half of what
`@sourced(...)` promises statically. A constant that disappears from this file is
a table whose reader stops being observable, so `--check` regenerates and
compares rather than trusting the version on disk.
"""

from __future__ import annotations

#: module -> {module-level constant: dataset stem it was loaded from or derived
#: from}. Derived constants are included on purpose: a projection computed at
#: import (`_CATEGORIE = sorted({v["categoria"] for v in _CATALOGO.values()})`) is
#: still the table, and reading it during a call means the call applied it.
TABLE_CONSTANTS: dict[str, dict[str, str]] = {
    "src.tools.atti_giudiziari": {
        "_CODICI_RUOLO": "codici_ruolo",
        "_CU": "contributo_unificato",
        "_TASSI_MORA": "tassi_mora",
        "_TRIBUNALI_COMPETENTI": "tribunali_competenti",
    },
    "src.tools.dichiarazione_redditi": {
        "_CODICI_TRIBUTO": "codici_tributo",
        "_IRPEF": "irpef_scaglioni",
        "_TASSI_LEGALI": "tassi_legali",
    },
    "src.tools.diritto_lavoro": {
        "_IRPEF": "irpef_scaglioni",
        "_PREAVVISO": "preavviso_ccnl",
    },
    "src.tools.fatturazione_avvocati": {
        "_COMPETENZE_PENALE": "parametri_forensi",
        "_CU_CIVILE": "contributo_unificato",
        "_PARAMETRI": "parametri_forensi",
    },
    "src.tools.modelli_atti": {
        "_CATALOGO": "modelli_atti",
        "_CATEGORIE": "modelli_atti",
    },
    "src.tools.privacy_gdpr": {
        "_BASI": "gdpr_basi_giuridiche",
        "_DPIA": "gdpr_dpia_criteri",
        "_SANZIONI": "gdpr_sanzioni",
    },
    "src.tools.procure_quotazioni": {
        "_CU": "contributo_unificato",
        "_PARAMETRI": "parametri_forensi",
    },
    "src.tools.proprieta_successioni": {
        "_SUCCESSIONE": "imposte_successione",
        "_USUFRUTTO": "usufrutto_coefficienti",
    },
    "src.tools.risarcimento_danni": {
        "_DANNO_BIO": "tabella_danno_bio",
        "_MACRO": "tabella_danno_bio",
        "_MICRO": "tabella_danno_bio",
        "_PARENTALE": "tabella_milano_roma",
    },
    "src.tools.rivalutazioni_istat": {
        "_COEFF_RACCORDO": "indici_foi",
        "_COEFF_RACCORDO_TESTO": "indici_foi",
        "_FOI_DATA": "indici_foi",
        "_INDICI_FOI": "indici_foi",
        "_NOTA_RACCORDO": "indici_foi",
        "_RACCORDO_BASI": "indici_foi",
        "_TASSI_LEGALI": "tassi_legali",
        "_VARIAZIONI_UFFICIALI": "indici_foi",
    },
    "src.tools.scadenze_termini": {
        "_FESTIVITA_FISSE": "festivita",
    },
    "src.tools.tassi_interessi": {
        "_TASSI_LEGALI": "tassi_legali",
        "_TASSI_MORA": "tassi_mora",
    },
    "src.tools.varie": {
        "_ATECO": "codici_ateco",
        "_COMUNI": "comuni",
        "_COMUNI_DATA": "comuni",
        "_FESTIVITA": "festivita",
        "_STATI_ESTERI": "comuni",
        "_VIOLAZIONI": "violazioni_patente",
    },
}

#: tool -> tables its code reads. The ledger observes the wrapped constants, so
#: this is not what the answer names; it is the fallback for the case where the
#: observation is blind (a table reached through a scalar computed at import),
#: where the declaration stays the best available statement -- and it is what
#: lets the middleware flag the vintage of a table it could not see being read.
TOOL_TABLES: dict[str, tuple[str, ...]] = {
    "adeguamento_canone_locazione": ("indici_foi",),
    "analisi_base_giuridica": ("gdpr_basi_giuridiche",),
    "calcolo_devalutazione": ("indici_foi",),
    "calcolo_inflazione": ("indici_foi",),
    "calcolo_irpef": ("irpef_scaglioni",),
    "calcolo_maggior_danno": ("indici_foi", "tassi_legali"),
    "calcolo_notula_penale": ("parametri_forensi",),
    "calcolo_sanzione_gdpr": ("gdpr_sanzioni",),
    "calcolo_tfr": ("irpef_scaglioni",),
    "calcolo_usufrutto": ("usufrutto_coefficienti",),
    "cerca_codice_tributo": ("codici_tributo",),
    "cerca_ufficio_giudiziario": ("tribunali_competenti",),
    "codice_fiscale": ("comuni",),
    "codici_iscrizione_ruolo": ("codici_ruolo",),
    "conta_giorni": ("festivita",),
    "contributo_unificato": ("contributo_unificato",),
    "costo_lavoro": ("irpef_scaglioni",),
    "danno_biologico_macro": ("tabella_danno_bio",),
    "danno_biologico_micro": ("tabella_danno_bio",),
    "danno_non_patrimoniale": ("tabella_danno_bio",),
    "danno_parentale": ("tabella_milano_roma",),
    "decodifica_codice_fiscale": ("comuni",),
    "decreto_ingiuntivo": ("contributo_unificato",),
    "decurtazione_punti_patente": ("violazioni_patente",),
    "detrazione_lavoro_dipendente": ("irpef_scaglioni",),
    "genera_modello_atto": ("modelli_atti",),
    "genera_quotazione_docx": ("contributo_unificato", "parametri_forensi"),
    "imposte_compravendita": ("imposte_successione",),
    "imposte_successione": ("imposte_successione",),
    "indennita_preavviso": ("preavviso_ccnl",),
    "inflazione_titoli_stato": ("indici_foi",),
    "interessi_acconti": ("tassi_legali",),
    "interessi_corso_causa": ("tassi_mora",),
    "interessi_legali": ("tassi_legali",),
    "interessi_mora": ("tassi_mora",),
    "interessi_vari_capitale_rivalutato": ("indici_foi", "tassi_legali"),
    "lettera_adeguamento_canone": ("indici_foi",),
    "lista_categorie_atti": ("modelli_atti",),
    "modello_notula": ("contributo_unificato", "parametri_forensi"),
    "note_iscrizione_ruolo": ("codici_ruolo", "contributo_unificato"),
    "parcella_avvocato_civile": ("parametri_forensi",),
    "parcella_avvocato_penale": ("parametri_forensi",),
    "parcella_stragiudiziale": ("parametri_forensi",),
    "parcella_volontaria_giurisdizione": ("parametri_forensi",),
    "preventivo_civile": ("contributo_unificato", "parametri_forensi"),
    "preventivo_stragiudiziale": ("parametri_forensi",),
    "preventivo_volontaria_giurisdizione": ("parametri_forensi",),
    "ravvedimento_operoso": ("tassi_legali",),
    "regime_forfettario": ("irpef_scaglioni",),
    "ricerca_codici_ateco": ("codici_ateco",),
    "rivalutazione_annuale_media": ("indici_foi",),
    "rivalutazione_mensile": ("indici_foi",),
    "rivalutazione_monetaria": ("indici_foi", "tassi_legali"),
    "rivalutazione_storica": ("indici_foi",),
    "rivalutazione_tfr": ("indici_foi",),
    "scadenza_processuale": ("festivita",),
    "scadenze_impugnazioni": ("festivita",),
    "scadenze_multe": ("festivita",),
    "sollecito_pagamento": ("tassi_mora",),
    "termini_183_190_cpc": ("festivita",),
    "termini_deposito_atti_appello": ("festivita",),
    "termini_deposito_ctu": ("festivita",),
    "termini_esecuzioni": ("festivita",),
    "termini_memorie_repliche": ("festivita",),
    "termini_procedimento_semplificato": ("festivita",),
    "termini_processuali_civili": ("festivita",),
    "termini_separazione_divorzio": ("festivita",),
    "variazioni_istat": ("indici_foi",),
    "verifica_mediazione_obbligatoria": ("mediazione_obbligatoria",),
    "verifica_necessita_dpia": ("gdpr_dpia_criteri",),
    "verifica_usura": ("tegm",),
}
